### ISSUE TITLE
[flask run] ImportError: cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by jiang13021** [opendilab/DI-sheep#1]
# 问题描述
我用conda创建了一个python版本为3.9.13的虚拟环境，按照要求安装了`requirement.txt`中的包。发现在执行
```shell
FLASK_APP=app.py flask run
```
的时候，出现了报错
```shell
Traceback (most recent call last):
  File "/Users/jiang13021/opt/anaconda3/envs/disheep/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/Users/jiang13021/opt/anaconda3/envs/disheep/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/Users/jiang13021/opt/anaconda3/envs/disheep/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/Users/jiangyzanze/opt/anaconda3/envs/disheep/lib/python3.9/site-packages/itsdangerous/__init__.py)
```

# 问题排查
发现是`itsdangerous`包版本的问题。在安装`flask==1.1.2`的时候，就默认安装`itsdangerous-2.1.2`。改为`itsdangerous-2.0.1`即可正常运行

# 修改意见
在`server/requirement.txt`中增加
```shell
itsdangerous==2.0.1
```
即可

**Comment by jiang13021** [comment]
顺便，希望可以在README中推荐使用conda的虚拟环境https://github.com/conda/conda#getting-started
方便新手配环境，也方便开发者以新手视角调试。
```shell
conda create --name disheep python=3.9
conda activate disheep
```

**Comment by PaParaZz1** [comment]
- itsdangerous==2.0.1这个问题对应的PR已merge
- python环境这个太基础了，不过如果后续问的人多的话，会考虑加一个node.js和python配置的推荐指南
